<a href="https://colab.research.google.com/github/Hrishikesh6666/Data_science/blob/main/Mastering_Numpay_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# IMPORT NUMPAY

In [ ]:
import numpy

In [ ]:
# NOTE = Random numbers are from zero to one
numpy.random.random()


0.6790530443409546

# Heads and Tails program

In [ ]:
import numpy

if numpy.random.random() < 0.5:

    print("Heads")               # Indent this line as well
else:
    print("Tails")

Heads


# TO CREATE A MATRIX OF RANDOM NUMBERS

In [ ]:
numpy.random.random((4,4))
#we can also use (2,2),(4,4)

array([[0.61794535, 0.3405384 , 0.84166902, 0.38855211],
       [0.10740173, 0.76442429, 0.88521966, 0.63475858],
       [0.90392633, 0.59120655, 0.07323219, 0.26043992],
       [0.84656715, 0.11517876, 0.37280199, 0.34143683]])

In [ ]:
# Generate the number based on the range her we can define what should be the
# (START, END, and what should be the DISTANCE)

numpy.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
# Use of (LINSPACE) to make it a line space which are equally distance
numpy.linspace(1,20,11).astype(float)

array([ 1. ,  2.9,  4.8,  6.7,  8.6, 10.5, 12.4, 14.3, 16.2, 18.1, 20. ])

# USE OF ARRAY IN NUMPAY0

In [ ]:
import numpy as np

In [ ]:
# the given matrix is stored as array
arr = np.random.random((4,4))
print(arr)

[[0.06989118 0.40584681 0.34800751 0.08629674]
 [0.17976761 0.19504795 0.48197837 0.43102086]
 [0.64909575 0.95499923 0.28014715 0.27183974]
 [0.11330536 0.78070363 0.61748994 0.49450867]]


In [ ]:
arr.shape

(4, 4)

In [ ]:
arr = arr.reshape(2,8)
print(arr)

[[0.06989118 0.40584681 0.34800751 0.08629674 0.17976761 0.19504795
  0.48197837 0.43102086]
 [0.64909575 0.95499923 0.28014715 0.27183974 0.11330536 0.78070363
  0.61748994 0.49450867]]


# **ARRAY FLATTE**N
(flatten means we are having 2 or 3 or
10 dimensional array that are flattern into 1(one) dimensional array*)

In [ ]:
arr = arr.flatten()
arr.shape
(2)
print(arr)

[0.06989118 0.40584681 0.34800751 0.08629674 0.17976761 0.19504795
 0.48197837 0.43102086 0.64909575 0.95499923 0.28014715 0.27183974
 0.11330536 0.78070363 0.61748994 0.49450867]


# 4) ARRAY TO LIST AND VIVE VERSE

In [ ]:
first_tuple = (1, 2, 3, 4, 5)
arr = np.array(first_tuple)
print(arr)

[1 2 3 4 5]


In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
#from array to list
first_tuple = list(arr)

In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
array = [(1,3,4,5,6,7)]

In [ ]:
for i in array:
  for num in i:
    print (num + 5)

6
8
9
10
11
12


ARITHMATIC OPERATION:


In [ ]:
arr = (1,2,3,4,5,6,7,8,9,10)


In [ ]:
for num in arr:
    print(int(num + 1))
    print(int(num - 1))
    print(int(num * 2))
    print(int(num / 2))
    print(int(num** 2))

2
0
2
0
1
3
1
4
1
4
4
2
6
1
9
5
3
8
2
16
6
4
10
2
25
7
5
12
3
36
8
6
14
3
49
9
7
16
4
64
10
8
18
4
81
11
9
20
5
100


In [ ]:
arr

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

In [ ]:

arr_np = np.array(arr)
print(arr_np.min())
print(arr_np.max())
print(arr_np.sum())
print(arr_np.mean())
''' It appears you are trying to use the .median() method on a NumPy array, but this method does not exist in NumPy.
 The median function is available in the numpy library, but it needs to be called as a function, not as a method on
 the array.'''

print(np.median(arr_np))

1
10
55
5.5
5.5


# ARITHEMATIC OPERATION ON MULTIPLE ARRAY

In [ ]:
arr1=np.array(([1,2,3],[4,5,6]))
arr2=np.array(([7,8,9],[10,11,12]))
arr3=np.array(([13,14,15],[16,17,18]))

In [ ]:
arr1+arr2+arr3

([1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18])

In [ ]:
arr1-arr2

array([[-6, -6, -6],
       [-6, -6, -6]])

In [ ]:
arr1*arr3

array([[ 13,  28,  45],
       [ 64,  85, 108]])

# ARRAY SLICING

In [ ]:
arr1=np.array((1,2,3,4,5,6,7,8,9,10))

In [ ]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr1[3]

4

In [ ]:
arr1[-4]

7

In [ ]:
arr[1:-1]

(2, 3, 4, 5, 6, 7, 8, 9)

# ARRAY SORTING

In [4]:
import numpy as np
arr1 = np.array([4,7,6,3,2,9,10,3,2,1,8])


In [5]:
arr1.sort()
print(arr1)

[ 1  2  2  3  3  4  6  7  8  9 10]


In [7]:
arr1.sort(kind='mergesort') ## you can use merge ,Quick ,bubble ,selection sort also
print(arr1)

[ 1  2  2  3  3  4  6  7  8  9 10]


In [8]:
arr2=np.array([[9,3,7],[8,6,2]])

*Sorting array by row and colums*

In [10]:
np.sort(arr2,axis=0)

array([[8, 3, 2],
       [9, 6, 7]])

In [9]:
np.sort(arr2,axis=1)

array([[3, 7, 9],
       [2, 6, 8]])

# ARRAY MERGING

In [16]:
arr3 = np.array([[1,2,3],[4,5,6]])
arr4 = np.array([[4,5,6],[7,8,9]])

**Using vstack , hstack command:**

In [22]:
v = np.vstack((arr3,arr4))
print(v)

[[1 2 3]
 [4 5 6]
 [4 5 6]
 [7 8 9]]


In [23]:
h =np.hstack((arr3,arr4))
print(h)

[[1 2 3 4 5 6]
 [4 5 6 7 8 9]]


***Using concatenate command***

In [19]:
np.concatenate((arr3,arr4),axis=1)

array([[1, 2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8, 9]])

In [20]:
np.concatenate((arr3,arr4),axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6],
       [7, 8, 9]])

# Array Spliting

In [26]:
newarr = np.array_split(h,3)
print(newarr)

[array([[1, 2, 3, 4, 5, 6]]), array([[4, 5, 6, 7, 8, 9]]), array([], shape=(0, 6), dtype=int64)]


# **Numpy Array Search (where)**

In [29]:
 x = np.array([1,23,22,45,6,4878,98,95,8,65,96,5,956,65,9,65,95,6])

In [33]:
x_np = np.array(x)
num = np.where(x_np % 2 == 0)
print(num)

(array([0, 0, 0, 0, 0, 0]), array([0, 1, 3, 4, 5, 6]))
