<a href="https://colab.research.google.com/github/Hrishikesh6666/Data_science/blob/main/Mastering_Numpay_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

IMPORT NUMPAY

In [ ]:
import numpy

In [ ]:
# NOTE = Random numbers are from zero to one
numpy.random.random()


0.6790530443409546

Heads and Tails program

In [ ]:
import numpy

if numpy.random.random() < 0.5:

    print("Heads")               # Indent this line as well
else:
    print("Tails")

Heads


TO CREATE A MATRIX OF RANDOM NUMBERS

In [ ]:
numpy.random.random((4,4))
#we can also use (2,2),(4,4)

array([[0.61794535, 0.3405384 , 0.84166902, 0.38855211],
       [0.10740173, 0.76442429, 0.88521966, 0.63475858],
       [0.90392633, 0.59120655, 0.07323219, 0.26043992],
       [0.84656715, 0.11517876, 0.37280199, 0.34143683]])

In [ ]:
# Generate the number based on the range her we can define what should be the
# (START, END, and what should be the DISTANCE)

numpy.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
# Use of (LINSPACE) to make it a line space which are equally distance
numpy.linspace(1,20,11).astype(float)

array([ 1. ,  2.9,  4.8,  6.7,  8.6, 10.5, 12.4, 14.3, 16.2, 18.1, 20. ])

USE OF ARRAY IN NUMPAY0

In [26]:
import numpy as np

In [28]:
# the given matrix is stored as array
arr = np.random.random((4,4))
print(arr)

[[0.14323323 0.88437079 0.90502871 0.22449833]
 [0.44620073 0.60390246 0.4344     0.60296028]
 [0.14237273 0.28203314 0.35736687 0.96588298]
 [0.22215107 0.21546071 0.9947037  0.26442237]]
